#!/usr/bin/env bash

. /root/.venv

# run Geneea analysis
sh $WORKFLOWS_FLODER/analyze-irozhlas/analyze_day_ago.sh > $LOGS/analyze-irozhlas/irozhlas-geneea_`date +%Y_%m_%d`.log 2>&1
#!/bin/bash

# commit logs
cd $LOGS_FOLDER
git add .
git commit -am "`date` irozhlas-geneea-analysis ran"
git pull --rebase
git push
