#!/bin/bash

. /root/.env

# Irozhlas scraper
cd /root/irozhlas/irozhlas-scraper
. /root/irozhlas/irozhlas-scraper/.venv/bin/activate
# logging optional
#irozhlas-scrape > /root/logs/analyze-irozhlas/irozhlas-scrape_`date +%Y_%m_%d_%H_%M_%S`.log 2>&1
irozhlas-scrape > /dev/null 2>&1
deactivate


sh /root/workflows/scrape_publicistika.sh > /root/irozhlas-scraper-geneea-output/publicistika/irozhlas-publicistika-scrape_`date +%Y_%m_%d`.log 2>&1

# logging optional
# commit logs
cd  /root/irozhlas-scraper-geneea-output/publicistika/
git add .
git commit -am "`date` irozhlas-publicistika-scrape ran"
git pull --rebase
git push
