#!/usr/bin/env bash

# NAME:
# arrange-openmedia-data
#
# DESCRIPTION:
# Run the `cro-openmedia-arrange` command.
#
# ENVIRONMENT:
# $ANNOVA: The path to exported OpenMedia files
#
# PARAMETERS: NONE
#

set -e

echo "Set and check environment"
echo "========================="

if [[ -n $ANNOVA ]]; then
    echo "Variable ANNOVA is not set";
    exit 1
fi

# Set variables for directory path construction.

YEAR=`date +%Y` # The current year.
WEEK=`date +%V` # The current week (number).

echo "The year/week path is ${YEAR} and ${WEEK}."
