#!/usr/bin/env bash

#
# Run the `cro-openmedia-arrange` command.
#

# Set varibles for direcotry path construction.
YEAR=`date +%Y` # The current year.
WEEK=`date +%V` # The current week (number).

echo "The week ${YEAR}/${WEEK}."

# Update programs to latest version.
echo "Pulling czech-radio/openmedia."
git pull --rebase origin main

echo "Activating virtual environment."
source /root/.venv/bin/activate

echo "Updating czech-radio/openmedia."
pip install -U /root/bin/openmedia

# Set the environment variables.
source /root/.env

# Run the programs.
echo "Runing cro-openmedia-arrange command."
cro-openmedia-arrange --input ${ANNOVA}

# Clean up and exit.
echo "Deactivating virtual environment."
deactivate

exit 0