#!/bin/bash

. /root/.env

#run openmedia-check /w changes to disk
sh $WORKFLOWS_FOLDER/process-openmedia-data/openmedia-check.sh

# commit logs
cd $LOGS_FOLDER
git add .
git commit -am "`date` openmedia-check ran"
git pull --rebase
git push

# run statistics
sh $WORKFLOWS_FOLDER/process-openmedia-data/stat-openmedia-data.sh

# commit logs
cd $LOGS_FOLDER
git add .
git commit -am "`date` stat-openmedia-data ran"
git pull --rebase
git push


# run openmedia-minify
sh $WORKFLOWS_FOLDER/process-openmedia-data/openmedia-minify.sh

# commit logs
cd $LOGS_FOLDER
git add .
git commit -am "`date` openmedia-minify ran"
git pull --rebase
git push


