#!/bin/bash

source /root/.env


#run openmedia-check /w changes to disk
#openmedia-check -i $ANNOVA -w 

# run statistics
./stat-openmedia-data

# commit logs
cd $LOGS_FOLDER
git commit -am "`date` stat-openmedia-data ran"
git pull --rebase
git push
